// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqstyqzybkppyghtiiso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxc3R5cXp5YmtwcHlnaHRpaXNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNjU5MjYsImV4cCI6MjA1Nzk0MTkyNn0.YzWL6msqeBZjVUAd4lLp-mQxPyVB66EsbHl6y1_RqJQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);